# Generated by Django 5.2.4 on 2025-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_images/')),
                ('role', models.CharField(max_length=100)),
                ('work', models.TextField(help_text='Short description of what they do')),
            ],
        ),
    ]
