# Generated by Django 5.2.4 on 2025-08-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('travels', 'Travels'), ('organization', 'Organization'), ('tips', 'Tips & Tricks'), ('uncategorized', 'Uncategorized'), ('latest', 'Latest News')], default='latest', max_length=50)),
            ],
        ),
    ]
